### PR TITLE
getOneUser and editUser

### PR DESCRIPTION
**Pull request by buaya123**
all needed for edit

### CODE REVIEW

**Comment by buaya123** [comment]
@FotieMConstant check my PR good sir

**Comment by buaya123** [comment]
ill make the changes shortly

**Comment by FotieMConstant** [comment]
Hey man, nice work there. However, I think it's better to use POST when passing data in the body of the request. equaly , can you use the URL params GET request when the param to be sent to the backend is just one value? like for the get one user. that would make thing nicer

and don't forget to mask users' info. checkout the recent changes I made

**Comment by buaya123** [comment]
i am using GET and params for getOneUser and using POST in passing data in body. could you be more specific?

**Comment by FotieMConstant** [comment]
Please can you resolve the conflicts before we merge

**Comment by FotieMConstant** [comment]
@buaya123 can one edit already. with the endpoint?

**Comment by buaya123** [comment]
Thats a yes @FotieMConstant

**Comment by buaya123** [comment]
oh wait, imma revise that one

**Pull request merged**
