### PR TITLE
Get bonded users

### PR DESCRIPTION
**Pull request by buaya123**
get bonded users end-point

### CODE REVIEW

**Review by quiet-programmer — COMMENTED** [review]
So I wanna know... I just went through the API doc you edited here and the Code... I didn't see any way where like we get to know which user is bond to which user?

**Review by quiet-programmer — DISMISSED** [review]
and yeah I think we should have a field in the user database where 

[
    {
        "uid":"uid of target",
        "name":"name of target",
        "username":"unsername of target",
        "email":"email of target",
        "photo":"photo of target"
        "bonded_user":"user uid or email"
    }
]

that is not available in the API yet... so how do we get to know which user is bond to which? I don't know if this is already available... if it is... please refer me to it... but for now that is what should be added first tho... Thanks man...

**Comment by FotieMConstant** [comment]
@quiet-programmer apparently his idea is to return the user Object to whom the current user is bond to. Remember we also need the "Roomid"

**Comment by quiet-programmer** [comment]
> @quiet-programmer apparently his idea is to return the user Object to whom the current user is bond to. Remember we also need the "Roomid"

my point is... how do we know the uid we are passing to the API?

**Comment by FotieMConstant** [comment]
> and yeah I think we should have a field in the user database where
> 
> [
> {
> "uid":"uid of target",
> "name":"name of target",
> "username":"unsername of target",
> "email":"email of target",
> "photo":"photo of target"
> "bonded_user":"user uid or email"
> }
> ]
> 
> that is not available in the API yet... so how do we get to know which user is bond to which? I don't know if this is already available... if it is... please refer me to it... but for now that is what should be added first tho... Thanks man...

@quiet-programmer Okay so if you check the db script or our PDM you will see that there is an association class between the Room and the User table which is bond. This table carries the foreign keys of both tables, from there it's easy for us to have a join and get the user who is in a room. So essentially we are paying around with the bond table and the room table, the room table is to store the socket room name we will user for the websockets and the bond table links that to the user.

**Comment by FotieMConstant** [comment]
> > @quiet-programmer apparently his idea is to return the user Object to whom the current user is bond to. Remember we also need the "Roomid"
> 
> my point is... how do we know the uid we are passing to the API?

simple, the uid of the currently logged in user. the user who's session is open on the browser

**Comment by quiet-programmer** [comment]
> > > @quiet-programmer apparently his idea is to return the user Object to whom the current user is bond to. Remember we also need the "Roomid"
> > 
> > 
> > my point is... how do we know the uid we are passing to the API?
> 
> simple, the uid of the currently logged in user. the user who's session is open on the browser

no no get it clear first... two users are bonded right? how do we know which users are bonded together?

**Comment by FotieMConstant** [comment]
@buaya123 @quiet-programmer I think essentially what we should have is something like
```
{
"uid": "uid of partner",
"name": "name of partner",
"username": "unsername of partner",
"email": "email of partner",
"photo": "photo of partner"
"roomId": "the room id they are linked to from the room table"
}
```
and here is the logic.

1. user auth
2. we check if bond exists
3. if yes { it returns the object we have above with room id } else { it returns not bonded yet code(not yet sure how we will have this stated in the response but I think you should get it)}
4. now if bond existed we use the info in the object to display to the user their partners profile info and the room id to establish a websocket connection.
5. they are connected and can start exchanging data

Get my point? not even sure if it makes that much sense. please guys let me know!

**Comment by buaya123** [comment]
oh yeah i shouldve returned bond_id also

**Comment by buaya123** [comment]
updated with roomname ,roomId , personDetails when fetching data

**Comment by buaya123** [comment]
@FotieMConstant @quiet-programmer check it again if its all good

**Review by quiet-programmer — COMMENTED** [review]
@FotieMConstant come check it out first

**Review by FotieMConstant — APPROVED** [review]
Hey @buaya123, thanks for this amazing PR. Everything looks great!

**Review by FotieMConstant — APPROVED** [review]

**Pull request merged**
