### PR TITLE
Added prettier and eslint plus related fixes/updates

### PR DESCRIPTION
**Pull request by vikashd**
I've added some configuration for linting and prettifying JS code to ensure consistency.

I've fixed up some linting errors but will fix up a few more if someone can test my changes and ensure it's all working as expected.

### CODE REVIEW

**Comment by FotieMConstant** [comment]
@vikashd conflicts

**Review by FotieMConstant — CHANGES_REQUESTED** [review]
Hi @vikashd, thanks for this amazing PR. Please could you resolve the conflicts before we merge. thanks

**Comment by quiet-programmer** [comment]
everything seems okay just fix the conflict so we can merge @vikashd

**Comment by vikashd** [comment]
@FotieMConstant Fixed that conflict and tidied up api.js as well as some other linting fixes. Can you please test to ensure everything is working. Thanks!

**Comment by FotieMConstant** [comment]
Hello @vikashd ...For some reason, your preview deployments are failing...
Here are the logs

`
07:53:19.607  	Cloning github.com/FotieMConstant/bond (Branch: app-config-updates, Commit: 6818df8)
07:53:19.979  	Cloning completed: 371.912ms
07:53:20.030  	Analyzing source code...
07:53:21.366  	Installing build runtime...
07:53:24.050  	Build runtime installed: 2.683s
07:53:28.462  	Build cache not provided
07:53:29.895  	Detected package.json
07:53:29.895  	Installing dependencies...
07:53:30.521  	npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
07:53:58.656  	> yorkie@2.0.0 install /vercel/path1/node_modules/yorkie
07:53:58.656  	> node bin/install.js
07:53:58.782  	CI detected, skipping Git hooks installation
07:53:58.869  	> core-js@3.6.5 postinstall /vercel/path1/node_modules/@firebase/polyfill/node_modules/core-js
07:53:58.869  	> node -e "try{require('./postinstall')}catch(e){}"
07:53:59.001  	> core-js@3.9.1 postinstall /vercel/path1/node_modules/core-js
07:53:59.001  	> node -e "try{require('./postinstall')}catch(e){}"
07:53:59.095  	> ejs@2.7.4 postinstall /vercel/path1/node_modules/ejs
07:53:59.095  	> node ./postinstall.js
07:53:59.267  	> protobufjs@6.10.2 postinstall /vercel/path1/node_modules/protobufjs
07:53:59.268  	> node scripts/postinstall
07:53:59.511  	> vuesax@4.0.1-alpha.25 postinstall /vercel/path1/node_modules/vuesax
07:53:59.511  	> node scripts/postinstall.js
07:53:59.626  	                                         
07:53:59.626  	                                         
07:53:59.626  	                          Thanks for installing Vuesax 
07:53:59.626  	                                         
07:53:59.627  	                     Please consider donating to our Patreon
07:53:59.627  	                        to help us maintain this package.
07:53:59.627  	                                         
07:53:59.627  	                Donate: https://www.patreon.com/bePatron?c=1567892
07:53:59.627  	                                         
07:53:59.627  	                                         
07:53:59.627  	                                         
07:54:00.891  	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
07:54:00.891  	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
07:54:00.900  	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
07:54:00.900  	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
07:54:00.911  	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
07:54:00.911  	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
07:54:00.918  	added 1518 packages from 736 contributors in 30.452s
07:54:01.913  	84 packages are looking for funding
07:54:01.913  	  run `npm fund` for details
07:54:02.199  	Running "npm run build"
07:54:02.477  	> bond@0.1.0 build /vercel/path1
07:54:02.477  	> vue-cli-service build
07:54:03.144  	-  Building for production...
07:54:05.238  	 ERROR  Failed to compile with 1 error6:54:05 AM
07:54:05.238  	Syntax Error: Thread Loader (Worker 0)
07:54:05.239  	No ESLint configuration found in /vercel/path1/src.
07:54:05.239  	You may use special comments to disable some warnings.
07:54:05.239  	Use // eslint-disable-next-line to ignore the next line.
07:54:05.240  	Use /* eslint-disable */ to ignore all warnings in a file.
07:54:05.240  	 ERROR  Build failed with errors.
07:54:05.255  	npm ERR! code ELIFECYCLE
07:54:05.255  	npm ERR! errno 1
07:54:05.259  	npm ERR! bond@0.1.0 build: `vue-cli-service build`
07:54:05.259  	npm ERR! Exit status 1
07:54:05.259  	npm ERR! 
07:54:05.259  	npm ERR! Failed at the bond@0.1.0 build script.
07:54:05.259  	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
07:54:05.271  	npm ERR! A complete log of this run can be found in:
07:54:05.271  	npm ERR!     /vercel/.npm/_logs/2021-05-01T06_54_05_260Z-debug.log
07:54:05.285  	Error: Command "npm run build" exited with 1
`

**Comment by vikashd** [comment]
@FotieMConstant Just made some updates, let me know if there are still problems.

**Comment by FotieMConstant** [comment]
same issues @vikashd 
image

**Review by FotieMConstant — APPROVED** [review]

**Comment by FotieMConstant** [comment]
Hey, @vikashd everything looks good now, however...the invite email endpoint is broken, it responds with 
````
A server error has occurred

FUNCTION_INVOCATION_FAILED
````

**Comment by FotieMConstant** [comment]
try `https://bond-api-git-fork-vikashd-app-config-updates-fotiemconstant.vercel.app/sendInvite/youremail_here`

This is the preview of your commit

**Comment by vikashd** [comment]
@FotieMConstant Is there more info in the logs?

**Comment by vikashd** [comment]
@FotieMConstant this looks like it's working now.

**Comment by FotieMConstant** [comment]
@vikashd all checks passed but please can you check the confligs?
Ready to merge

**Comment by vikashd** [comment]
@FotieMConstant Just pushed up some fixes to resolve the conflict. Please test again as there were quite a few changes.

**Comment by vikashd** [comment]
@FotieMConstant can we get this merged in ASAP (if it's all good) because I keep having to fix conflicts 😅.

**Review by FotieMConstant — APPROVED** [review]
Hi, @vikashd Thanks for this amazing PR. Everything looks clean. Also, sorry for the delay to merge been working on quite a lot lately!

**Pull request merged**
