### PR TITLE
updated readme to dev

### PR DESCRIPTION
**Pull request by buaya123**

### CODE REVIEW

**Comment by buaya123** [comment]
I forgot there was an existing request, but bondUsers , okok/node-api/readme , bond/readme is there

**Comment by buaya123** [comment]
wait theres a few bugs there

**Comment by buaya123** [comment]
@FotieMConstant Check this out

**Comment by buaya123** [comment]
hmmm preview didnt work for me, weird

**Comment by buaya123** [comment]
is this related to me npm installing a module? or as long as i pass in package.json its fine?

**Comment by buaya123** [comment]
what is happening

**Comment by FotieMConstant** [comment]
@buaya123 It should be a bug or something. please try check it out

**Comment by buaya123** [comment]
yeah , on it

**Comment by buaya123** [comment]
found the damn bug

**Comment by buaya123** [comment]
looks cool?

**Review by FotieMConstant — APPROVED** [review]

**Review by FotieMConstant — APPROVED** [review]
Hey @buaya123 thanks for this amazing PR!

**Comment by FotieMConstant** [comment]
Everything looks great to me. still have to test the endpoint tho.

**Pull request merged**
