### PR TITLE
updated packages and migrated app to Flutter 2.0

### PR DESCRIPTION
**Pull request by quiet-programmer**

### CODE REVIEW

**Comment by quiet-programmer** [comment]
Please do not merge this PR.... did to fix something in it

**Comment by FotieMConstant** [comment]
Hey @quiet-programmer are we merging this? or what... Hahah

**Comment by quiet-programmer** [comment]
> Hey @quiet-programmer are we merging this? or what... Hahah

if you check you will see the check I did for the app, did not pass... something went wrong, because I have not modified the code to fully Flutter 2.0, I have been busy with classes that's why

**Comment by quiet-programmer** [comment]
@FotieMConstant just fixed the broken code and successfully migrated app to Flutter 2.0 Null-Safety, everything working fine now

**Pull request merged**
