### PR TITLE
New web firebase user modifier and Documentation init!

### PR DESCRIPTION
**Pull request by RonaldColyar**
This PR merges functionality of basic user functionality by using the firebase web api. You would make an instance of this class and use it to do firebase queries.

### CODE REVIEW

**Comment by RonaldColyar** [comment]
@FotieMConstant @quiet-programmer @dilanlongla

**Review by FotieMConstant — APPROVED** [review]
Hi, @RonaldColyar Thanks for this amazing PR. I think we should have to talk about this. If finally, we will go for firebase of MongoDB or PostreSQL

**Comment by FotieMConstant** [comment]
@quiet-programmer @dilanlongla Could you please have a look at this before we merge? 
Thanks!

**Comment by dilanlongla** [comment]
sure @FotieMConstant

**Pull request closed without merging**
